# -*- coding: utf-8 -*-
"""Predicting_Quality_of_Transmission_of_Optical_Network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10BmLdpgcyUywVUN-w4Vi0Eu82sgr9xMO

#**Predicting the Quality of Transmission of Unestablished Optical Network Channels Using Deep Learning Models**

#**4. METHODS**

**Obtain the Simulation Sofware**
"""

! git clone https://github.com/Telecominfraproject/oopt-gnpy # clone the repo
! cd oopt-gnpy
#! pip install --editable . # note the trailing dot

"""**Import Dependencies/Libraries**"""

# Commented out IPython magic to ensure Python compatibility.
import sys, os
import pandas as pd
import numpy as np
from IPython.display import display
import datetime
import time
import IPython
import IPython.display
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.dates as mpl_dates
import numpy as np
import pandas as pd
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from scipy.stats import reciprocal
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from pydrive.auth import GoogleAuth
from google.colab import drive
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
import scipy as sp
import scipy.fftpack
# %matplotlib inline
import itertools
import logging
from multiprocessing import Pool
from typing import Dict, List, Optional, Sequence, Tuple, Union
from matplotlib.dates import DateFormatter
import matplotlib.dates as mdates
from statsmodels.graphics.tsaplots import plot_acf
from sklearn.preprocessing import Normalizer
from tensorflow.keras import layers
from IPython.display import Image
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from keras.layers import Conv2D, Conv1D, MaxPooling2D, MaxPooling1D, Flatten, BatchNormalization, Dense, LSTM, Dropout, Bidirectional
from keras.models import Sequential

### Import our modules
import python_utils
import utils
from tsaug.visualization import plot

"""**Mount the Google Drive**"""

# Change Directory
from google.colab import drive
drive.mount('/content/gdrive/')

"""**Upload the Simulation Training Data from the Gaussian Model Software for the Optical Communication network between Sheffield to London and Sheffield to Endinburgh.**"""

# Training Set - Optical Network from Sheffield to London and Ffom Sheffield to Endingurgh
df_train = pd.read_csv('/content/gdrive/MyDrive/Sheffield_London__Sheffield_Endinburgh_35_TRAIN.csv')

# Testing Set - Optical Network from Belfast to Glasgow
df_test = pd.read_csv('/content/gdrive/MyDrive/Belfast_Glasgow_35_TEST.csv')

# Upload the Network Diagrams
Network_Sheffield_London = '/content/gdrive/MyDrive/newplot (1).png'
Image(filename = Network_Sheffield_London, width=500, height=300)

"""**Upload the Network Diagrams 2**"""

Network_Sheffield_Endinburgh = '/content/gdrive/MyDrive/newplot (2).png'
Image(filename = Network_Sheffield_Endinburgh, width=500, height=300)

"""**View the Training Dataset**"""

df_train

"""**View the Testing Dataset**"""

df_test

"""**Look at the statistics of the training dataset:**"""

df_train.describe().transpose()

"""**Look at the statistics of the testing dataset**"""

df_test.describe().transpose()

"""**Data Pre-processing - Evolution of a few features over Channel Frequency (THz):**"""

plot_cols = ['Channel power (dBm)', 'OSNR ASE (signal bw, dB)', 'SNR NLI (signal bw, dB)', 'SNR total (signal bw, dB)']
plot_features = df_train[plot_cols]
plot_features.index = df_train['Channel frequency (THz)']
_ = plot_features.plot(subplots=True, figsize=(15, 12))

# Set x-axis label
plt.xlabel('Channel frequency (THz)', weight='bold').set_fontsize('18')
plt.suptitle('Input Data for Training', weight='bold').set_fontsize('18')

# Saving the Images:
plt.savefig('Input Data for Modeling.png')

"""**Make X & Y Variables from the Data, and Perform Data Splitting - 80% train set and 20% val set**"""

# For Training Set:
y_ = df_train['SNR total (signal bw, dB)']
x_ = df_train.iloc[:, :-1]

# For Testing Set:
y_test = df_test['SNR total (signal bw, dB)']
X_test = df_test.iloc[:, :-1]

X_train, X_val, y_train, y_val = train_test_split(x_, y_, test_size=0.20, random_state=42)

"""**Normalize the data:**

It is important to scale features before training a neural network. Normalization is a common way of doing this scaling: subtract the mean and divide by the standard deviation of each feature.
"""

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_val)
X_test = scaler.transform(X_test)

# Convert the targets to arrays:
y_train = y_train.values
y_val = y_val.values
y_test = y_test.values

"""**Peek at the distribution of the features**"""

train_mean = df_train.mean()
train_std = df_train.std()

df_std = (df_train - train_mean) / train_std
df_std = df_std.melt(var_name='Column', value_name='Normalized')
plt.figure(figsize=(12, 6))
ax = sns.violinplot(x='Column', y='Normalized', data=df_std)
_ = ax.set_xticklabels(df_train.keys(), rotation=90)

# Some features do have long tails, but there are no obvious errors.

"""**Define Random Seed**"""

keras.backend.clear_session()
np.random.seed(42)
tf.random.set_seed(42)

"""**Define the Evaluation Metrics**"""

def MAE(pred, true):
    return tf.reduce_mean(tf.abs(pred - true))


def MSE(pred, true):
    return tf.reduce_mean((pred - true) ** 2)


def RMSE(pred, true):
    return tf.sqrt(MSE(pred, true))


def MAPE(pred, true):
    return tf.reduce_mean(tf.abs((pred - true) / true)) * 100


def metric(pred, true):
    mae = MAE(pred, true)
    mse = MSE(pred, true)
    rmse = RMSE(pred, true)
    mape = MAPE(pred, true)

    return mae, mse, rmse, mape

"""**Print the shape of the dataset**"""

print(X_train.shape)
print(X_val.shape)
print(X_test.shape)
print(y_train.shape)
print(y_val.shape)
print(y_test.shape)

"""**Model 1 - Random Forest (RF) Regressor:**

Here, we use Random Forest Regressor to fit to our training dataset & predict results.
"""

# instantiate the Regressor and fit to training data
start = time.time()

rf = RandomForestRegressor()
rf.fit(X_train, y_train)

end = time.time()
print('Time Taken: %.3f seconds' % (end-start))

# viewing params of random forest
rf.get_params()

all_models = list()
performance_all = {}

# making predictions on test set
start = time.time()

y_pred_rf = rf.predict(X_test)

end = time.time()
print('Time Taken: %.3f seconds' % (end-start))

print('Mean Absolute Error:', MAE(y_pred_rf, y_test))
print('Root Mean Square Error:', RMSE(y_pred_rf, y_test))
print('Mean Absolute Percentage Error:', MAPE(y_pred_rf, y_test))

performance_all['RF_Model'] = MAE(y_pred_rf, y_test), RMSE(y_pred_rf, y_test), MAPE(y_pred_rf, y_test)

model1 = rf
all_models.append(model1)

"""**Data Pre-processing for Model 2**"""

"""
    Upload the Simulation Training Data from the Gaussian Model Software for the Optical
    Communication network between Sheffield to London and Sheffield to Endinburgh.
"""
# Training Set - Optical Network from Sheffield to London and Ffom Sheffield to Endingurgh
df_train = pd.read_csv('/content/gdrive/MyDrive/Sheffield_London__Sheffield_Endinburgh_35_TRAIN.csv')

# Testing Set - Optical Network from Belfast to Glasgow
df_test = pd.read_csv('/content/gdrive/MyDrive/Belfast_Glasgow_35_TEST.csv')

"""
   i. Make X & Y Variables from the Data:
"""
# For Training Set:
y_ = df_train['SNR total (signal bw, dB)']
x_ = df_train.iloc[:, :-1]

# For Testing Set:
y_test = df_test['SNR total (signal bw, dB)']
X_test = df_test.iloc[:, :-1]

"""
   ii. Data Splitting - 80% train set and 20% val set:
"""
X_train, X_val, y_train, y_val = train_test_split(x_, y_, test_size=0.20, random_state=42)

"""
    Normalize the data:
    It is important to scale features before training a neural network. Normalization is a
    common way of doing this scaling: subtract the mean and divide by the standard deviation
    of each feature.
"""

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_val)
X_test = scaler.transform(X_test)

# Convert the targets to arrays:
y_train = y_train.values
y_val = y_val.values
y_test = y_test.values

"""**Model 2 - Support Vector Machine (SVM):**

Similar to RF Model, we'll fit SVM on our training dataset and check its performance on test data.
"""

# instantiate and fit SVM to train data

svc = SVR(C=1.0, epsilon=0.2)
clf = svc
clf.fit(X_train, y_train)

# check parameters of SVM
clf.get_params()

# making predictions on test set
start = time.time()

y_pred_svc = clf.predict(X_test)

end = time.time()
print('Time Taken: %.3f seconds' % (end-start))

print('Mean Absolute Error:', MAE(y_pred_svc, y_test))
print('Root Mean Square Error:', RMSE(y_pred_svc, y_test))
print('Mean Absolute Percentage Error:', MAPE(y_pred_svc, y_test))

performance_all['SVC_Model'] = MAE(y_pred_svc, y_test), RMSE(y_pred_svc, y_test), MAPE(y_pred_svc, y_test)

model2 = clf
all_models.append(model2)

"""**Data Pre-processing for Model 3**"""

"""
    Upload the Simulation Training Data from the Gaussian Model Software for the Optical
    Communication network between Sheffield to London and Sheffield to Endinburgh.
"""
# Training Set - Optical Network from Sheffield to London and Ffom Sheffield to Endingurgh
df_train = pd.read_csv('/content/gdrive/MyDrive/Sheffield_London__Sheffield_Endinburgh_35_TRAIN.csv')

# Testing Set - Optical Network from Belfast to Glasgow
df_test = pd.read_csv('/content/gdrive/MyDrive/Belfast_Glasgow_35_TEST.csv')

"""
   i. Make X & Y Variables from the Data:
"""
# For Training Set:
y_ = df_train['SNR total (signal bw, dB)']
x_ = df_train.iloc[:, :-1]

# For Testing Set:
y_test = df_test['SNR total (signal bw, dB)']
X_test = df_test.iloc[:, :-1]

"""
   ii. Data Splitting - 80% train set and 20% val set:
"""
X_train, X_val, y_train, y_val = train_test_split(x_, y_, test_size=0.20, random_state=42)

"""
    Normalize the data:
    It is important to scale features before training a neural network. Normalization is a
    common way of doing this scaling: subtract the mean and divide by the standard deviation
    of each feature.
"""

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_val)
X_test = scaler.transform(X_test)

# Convert the targets to arrays:
y_train = y_train.values
y_val = y_val.values
y_test = y_test.values

"""**Model 3:**

Build a Simple Multi-Layer Perceptron (MLP) Regression Model Uisng Subclassing API And Optimize the Hyperparameters:
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard

def build_model(n_hidden=1, n_neurons=30, learning_rate=3e-3, input_shape=[6]):
    model = keras.models.Sequential()
    model.add(keras.layers.InputLayer(input_shape=input_shape))
    for layer in range(n_hidden):
        model.add(keras.layers.Dense(n_neurons, kernel_initializer="he_normal", activation="relu"))
        model.add(keras.layers.BatchNormalization())
        model.add(keras.layers.Activation("relu"))
    model.add(keras.layers.Dense(1))
    optimizer = keras.optimizers.SGD(learning_rate=learning_rate)
    model.compile(loss="mse", optimizer=optimizer, metrics=[MAE, RMSE, MAPE])
    return model

early_stopping_cb = keras.callbacks.EarlyStopping(patience=10)
model_checkpoint_cb = keras.callbacks.ModelCheckpoint("MLP.h5", save_best_only=True)
run_index = 1 # increment every time you train the model
run_logdir = os.path.join(os.curdir, "my_MLP_logs", "run_bn_{:03d}".format(run_index))
tensorboard_cb = keras.callbacks.TensorBoard(run_logdir)
callbacks = [early_stopping_cb, model_checkpoint_cb, tensorboard_cb]

"""
    Hyperparameters Optimization Using Randomized Search Algorithm
"""
keras_reg = keras.wrappers.scikit_learn.KerasRegressor(build_model)

param_distribs = {
    "n_hidden": [1, 2, 3],
    "n_neurons": np.arange(1, 100)               .tolist(),
    "learning_rate": reciprocal(3e-4, 3e-2)      .rvs(1000).tolist(),
}

rnd_search_cv = RandomizedSearchCV(keras_reg, param_distribs, n_iter=10, cv=3, verbose=2)
rnd_search_cv.fit(X_train, y_train, epochs=10,
                  validation_data=(X_val, y_val),
                  callbacks=callbacks)

"""**Obtain the best Parameters, Score, trained model, and use it for evaluation**"""

print(rnd_search_cv.best_params_)
print(rnd_search_cv.best_score_)
rnd_search_cv.score(X_test, y_test)

model = rnd_search_cv.best_estimator_.model
model.evaluate(X_test, y_test)

"""**Make Predictions with the best trained Model:**"""

y_pred_MLP = model.predict(X_test)
performance_all['MLP_Model'] = MAE(y_pred_MLP, y_test), RMSE(y_pred_MLP, y_test), MAPE(y_pred_MLP, y_test)

"""**View the Model's Structure**"""

model.summary()

"""**Data Pre-processing for Model 4**"""

"""
    Upload the Simulation Training Data from the Gaussian Model Software for the Optical
    Communication network between Sheffield to London and Sheffield to Endinburgh.
"""
# Training Set - Optical Network from Sheffield to London and Ffom Sheffield to Endingurgh
df_train = pd.read_csv('/content/gdrive/MyDrive/Sheffield_London__Sheffield_Endinburgh_35_TRAIN.csv')

# Testing Set - Optical Network from Belfast to Glasgow
df_test = pd.read_csv('/content/gdrive/MyDrive/Belfast_Glasgow_35_TEST.csv')

"""
   i. Make X & Y Variables from the Data:
"""
# For Training Set:
y_ = df_train['SNR total (signal bw, dB)']
x_ = df_train.iloc[:, :-1]

# For Testing Set:
y_test = df_test['SNR total (signal bw, dB)']
X_test = df_test.iloc[:, :-1]

"""
   ii. Data Splitting - 80% train set and 20% val set:
"""
X_train, X_val, y_train, y_val = train_test_split(x_, y_, test_size=0.20, random_state=42)

"""
    Normalize the data:
    It is important to scale features before training a neural network. Normalization is a
    common way of doing this scaling: subtract the mean and divide by the standard deviation
    of each feature.
"""

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_val)
X_test = scaler.transform(X_test)

# Convert the targets to arrays:
y_train = y_train.values
y_val = y_val.values
y_test = y_test.values

"""**Model 4 - Convolutional Neural Network (CNN)**

**Compile, Build, and Perform Hyperparameters Optimization in order to Build the Deep Learning CNN Model:**

We will apply the CNN algorithm to our data to generate prediction results. First, we need to reshape our data for CNN.

We will use 1-dimensional CNN for our model, reshaping our data as per the dimensions of our CNN

Note that the timeseries data used here are univariate, meaning we only have one channel per timeseries example.
We will therefore transform the timeseries into a multivariate one with one channel using a simple
reshaping via numpy. This will allow us to construct a model that is easily applicable to multivariate time series


"""

# Commented out IPython magic to ensure Python compatibility.
X_val = X_val.values
# Reshape the Data:
X_train = X_train.reshape(len(X_train), X_train.shape[1], 1)
X_val = X_val.reshape(len(X_val), X_val.shape[1], 1)
X_test = X_test.reshape(len(X_test), X_test.shape[1], 1)
print(X_train.shape, X_val, X_test.shape)

# %load_ext tensorboard

def build_model(n_hidden=1, n_neurons=30, learning_rate=3e-3, input_shape=(6, 1)):
    model = keras.models.Sequential()
    model.add(keras.layers.InputLayer(input_shape=input_shape))
    for layer in range(n_hidden):
        model.add(Conv1D(n_neurons, kernel_size=2, activation='relu',
                    padding='same', input_shape=(6, 1)))
        model.add(keras.layers.BatchNormalization())
        model.add(MaxPooling1D(pool_size=(3), strides=2, padding='same'))
        model.add(keras.layers.Activation("relu"))
        model.add(Dropout(0.2))
    model.add(keras.layers.Dense(1))
    optimizer = keras.optimizers.SGD(learning_rate=learning_rate)
    model.compile(loss="mse", optimizer=optimizer, metrics=[MAE, RMSE, MAPE])
    return model

early_stopping_cb = keras.callbacks.EarlyStopping(patience=10)
model_checkpoint_cb = keras.callbacks.ModelCheckpoint("CNN.h5", save_best_only=True)
run_index = 1 # increment every time you train the model
run_logdir = os.path.join(os.curdir, "my_CNN_logs", "run_bn_{:03d}".format(run_index))
tensorboard_cb = keras.callbacks.TensorBoard(run_logdir)
callbacks = [early_stopping_cb, model_checkpoint_cb, tensorboard_cb]

"""
    Hyperparameters Optimization Using Randomized Search Algorithm
"""
keras_reg = keras.wrappers.scikit_learn.KerasRegressor(build_model)

param_distribs = {
    "n_hidden": [1, 2, 3],
    "n_neurons": np.arange(1, 100)               .tolist(),
    "learning_rate": reciprocal(3e-4, 3e-2)      .rvs(1000).tolist(),
}

rnd_search_cv = RandomizedSearchCV(keras_reg, param_distribs, n_iter=10, cv=3, verbose=2)
rnd_search_cv.fit(X_train, y_train, epochs=10,
                  validation_data=(X_val, y_val),
                  callbacks=callbacks)

"""**Obtain the best Parameters, Score, Best Trained Model and Use it for Evaluation**"""

print(rnd_search_cv.best_params_)
print(rnd_search_cv.best_score_)
rnd_search_cv.score(X_test, y_test)

model = rnd_search_cv.best_estimator_.model
model.evaluate(X_test, y_test)

"""**Make Predictions with the trained Model**"""

y_pred_CNN = model.predict(X_test)
performance_all['CNN_Model'] = MAE(y_pred_CNN, y_test), RMSE(y_pred_CNN, y_test), MAPE(y_pred_CNN, y_test)

"""**View the Model's Structure**"""

model.summary()

"""**Data Pre-processing for Model 5**"""

"""
    Upload the Simulation Training Data from the Gaussian Model Software for the Optical
    Communication network between Sheffield to London and Sheffield to Endinburgh.
"""
# Training Set - Optical Network from Sheffield to London and Ffom Sheffield to Endingurgh
df_train = pd.read_csv('/content/gdrive/MyDrive/Sheffield_London__Sheffield_Endinburgh_35_TRAIN.csv')

# Testing Set - Optical Network from Belfast to Glasgow
df_test = pd.read_csv('/content/gdrive/MyDrive/Belfast_Glasgow_35_TEST.csv')

"""
   i. Make X & Y Variables from the Data:
"""
# For Training Set:
y_ = df_train['SNR total (signal bw, dB)']
x_ = df_train.iloc[:, :-1]

# For Testing Set:
y_test = df_test['SNR total (signal bw, dB)']
X_test = df_test.iloc[:, :-1]

"""
   ii. Data Splitting - 80% train set and 20% val set:
"""
X_train, X_val, y_train, y_val = train_test_split(x_, y_, test_size=0.20, random_state=42)

"""
    Normalize the data:
    It is important to scale features before training a neural network. Normalization is a
    common way of doing this scaling: subtract the mean and divide by the standard deviation
    of each feature.
"""

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_val)
X_test = scaler.transform(X_test)

# Convert the targets to arrays:
y_train = y_train.values
y_val = y_val.values
y_test = y_test.values

"""**Model 5 - Build the Long Short Term Memory Neural Network (LSTM) and Perform Hyperparameters Optimization Using Randomized Search Algorithm**"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard

def build_model(n_hidden=1, n_neurons=30, learning_rate=3e-3, input_shape=(6, 1)):
    model = keras.models.Sequential()
    model.add(keras.layers.InputLayer(input_shape=input_shape))
    for layer in range(n_hidden):
        model.add(keras.layers.LSTM(n_neurons, return_sequences=True, activation="relu"))
        model.add(keras.layers.BatchNormalization())
        model.add(keras.layers.Activation("relu"))
        model.add(Dropout(0.2))
    model.add(keras.layers.Dense(1))
    optimizer = keras.optimizers.SGD(learning_rate=learning_rate)
    model.compile(loss="mse", optimizer=optimizer, metrics=[MAE, RMSE, MAPE])
    return model

early_stopping_cb = keras.callbacks.EarlyStopping(patience=10)
model_checkpoint_cb = keras.callbacks.ModelCheckpoint("LSTM.h5", save_best_only=True)
run_index = 1 # increment every time you train the model
run_logdir = os.path.join(os.curdir, "my_LSTM_logs", "run_bn_{:03d}".format(run_index))
tensorboard_cb = keras.callbacks.TensorBoard(run_logdir)
callbacks = [early_stopping_cb, model_checkpoint_cb, tensorboard_cb]

"""
    Hyperparameters Optimization Using Randomized Search Algorithm
"""
keras_reg = keras.wrappers.scikit_learn.KerasRegressor(build_model)

param_distribs = {
    "n_hidden": [1, 2, 3],
    "n_neurons": np.arange(1, 100)               .tolist(),
    "learning_rate": reciprocal(3e-4, 3e-2)      .rvs(1000).tolist(),
}

rnd_search_cv = RandomizedSearchCV(keras_reg, param_distribs, n_iter=10, cv=3, verbose=2)
rnd_search_cv.fit(X_train, y_train, epochs=10,
                  validation_data=(X_val, y_val),
                  callbacks=callbacks)

"""**Obtain the best Parameters, Score, and Best Trained Model and Use it for Evaluation**"""

print(rnd_search_cv.best_params_)
print(rnd_search_cv.best_score_)
rnd_search_cv.score(X_test, y_test)

model = rnd_search_cv.best_estimator_.model
model.evaluate(X_test, y_test)

"""**Make Predictions with the Best trained Model:**"""

y_pred_LSTM = model.predict(X_test)
performance_all['LSTM_Model'] = MAE(y_pred_LSTM, y_test), RMSE(y_pred_LSTM, y_test), MAPE(y_pred_LSTM, y_test)

"""**View the Model's Structure**"""

model.summary()

"""**Data Pre-processing for Model 6**"""

"""
    Upload the Simulation Training Data from the Gaussian Model Software for the Optical
    Communication network between Sheffield to London and Sheffield to Endinburgh.
"""
# Training Set - Optical Network from Sheffield to London and Ffom Sheffield to Endingurgh
df_train = pd.read_csv('/content/gdrive/MyDrive/Sheffield_London__Sheffield_Endinburgh_35_TRAIN.csv')

# Testing Set - Optical Network from Belfast to Glasgow
df_test = pd.read_csv('/content/gdrive/MyDrive/Belfast_Glasgow_35_TEST.csv')

"""
   i. Make X & Y Variables from the Data:
"""
# For Training Set:
y_ = df_train['SNR total (signal bw, dB)']
x_ = df_train.iloc[:, :-1]

# For Testing Set:
y_test = df_test['SNR total (signal bw, dB)']
X_test = df_test.iloc[:, :-1]

"""
   ii. Data Splitting - 80% train set and 20% val set:
"""
X_train, X_val, y_train, y_val = train_test_split(x_, y_, test_size=0.20, random_state=42)

"""
    Normalize the data:
    It is important to scale features before training a neural network. Normalization is a
    common way of doing this scaling: subtract the mean and divide by the standard deviation
    of each feature.
"""

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_val)
X_test = scaler.transform(X_test)

# Convert the targets to arrays:
y_train = y_train.values
y_val = y_val.values
y_test = y_test.values

"""**Model 6 - Gated Recurrent Unit Neural Network (GRU) and Perform Hyperparameters Optimization Using Randomized Search Algorithm**"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard

def build_model(n_hidden=1, n_neurons=30, learning_rate=3e-3, input_shape=(6, 1)):
    model = keras.models.Sequential()
    model.add(keras.layers.InputLayer(input_shape=input_shape))
    for layer in range(n_hidden):
        model.add(keras.layers.GRU(n_neurons, return_sequences=True, activation="relu"))
        model.add(keras.layers.BatchNormalization())
        model.add(keras.layers.Activation("relu"))
        model.add(Dropout(0.2))
    model.add(keras.layers.Dense(1))
    optimizer = keras.optimizers.SGD(learning_rate=learning_rate)
    model.compile(loss="mse", optimizer=optimizer, metrics=[MAE, RMSE, MAPE])
    return model

early_stopping_cb = keras.callbacks.EarlyStopping(patience=10)
model_checkpoint_cb = keras.callbacks.ModelCheckpoint("GRU.h5", save_best_only=True)
run_index = 1 # increment every time you train the model
run_logdir = os.path.join(os.curdir, "my_GRU_logs", "run_bn_{:03d}".format(run_index))
tensorboard_cb = keras.callbacks.TensorBoard(run_logdir)
callbacks = [early_stopping_cb, model_checkpoint_cb, tensorboard_cb]

"""
    Hyperparameters Optimization Using Randomized Search Algorithm
"""
keras_reg = keras.wrappers.scikit_learn.KerasRegressor(build_model)

param_distribs = {
    "n_hidden": [1, 2, 3],
    "n_neurons": np.arange(1, 100)               .tolist(),
    "learning_rate": reciprocal(3e-4, 3e-2)      .rvs(1000).tolist(),
}

rnd_search_cv = RandomizedSearchCV(keras_reg, param_distribs, n_iter=10, cv=3, verbose=2)
rnd_search_cv.fit(X_train, y_train, epochs=10,
                  validation_data=(X_val, y_val),
                  callbacks=callbacks)

"""**Obtain the best Parameters, Score, Best Trained Model and Use it for Evaluation**"""

print(rnd_search_cv.best_params_)
print(rnd_search_cv.best_score_)
rnd_search_cv.score(X_test, y_test)

model = rnd_search_cv.best_estimator_.model
model.evaluate(X_test, y_test)

"""**Make Predictions with the Best trained Model**"""

y_pred_GRU = model.predict(X_test)
performance_all['GRU_Model'] = MAE(y_pred_GRU, y_test), RMSE(y_pred_GRU, y_test), MAPE(y_pred_GRU, y_test)

"""**View the Model's Structure**"""

model.summary()

performance_all

"""**Performance Comparison of All DL Models - MAE**"""

x = np.arange(len(performance_all))
width = 0.5
metric_name = 'MAE'
metric_index = model.metrics_names.index('MAE')
test_accuracy = [v[metric_index] for v in performance_all.values()]

plt.figure(figsize=(15, 6))
plt.ylabel("MAE", weight='bold').set_fontsize('18')
#plt.bar(x - 0.17, val_accuracy, width, label='Validation')
plt.bar(x + 0.17, test_accuracy, width, label='Test', color = 'darkorange')
plt.xticks(ticks=x, labels=performance_all.keys(),
           rotation=90, size = 16, fontweight='bold')
plt.title('Performance Comparison of All DL Models - MAE', size = 22, fontweight='bold')
_ = plt.legend(loc = 2, bbox_to_anchor = (1.0, 1.0), ncol = 1, frameon=True, fontsize = '22')
plt.grid(True)
plt.savefig('Performance Comparison of All DL Models-MAE.png')

"""**Performance Comparison of All DL Models - RMSE**"""

x = np.arange(len(performance_all))
width = 0.5
metric_name = 'RMSE'
metric_index = model.metrics_names.index('RMSE')
test_accuracy = [v[metric_index] for v in performance_all.values()]

plt.figure(figsize=(15, 6))
plt.ylabel("RMSE", weight='bold').set_fontsize('18')
#plt.bar(x - 0.17, val_accuracy, width, label='Validation')
plt.bar(x + 0.17, test_accuracy, width, label='Test', color = 'green')
plt.xticks(ticks=x, labels=performance_all.keys(),
           rotation=90, size = 16, fontweight='bold')
plt.title('Performance Comparison of All DL Models - RMSE', size = 22, fontweight='bold')
_ = plt.legend(loc = 2, bbox_to_anchor = (1.0, 1.0), ncol = 1, frameon=True, fontsize = '22')
plt.grid(True)
plt.savefig('Performance Comparison of All DL Models-RMSE.png')

performance_all.values()

"""**Performance Comparison between All ML and DL Models in terms of all Metrics Before Augmentation**"""

RF_Model = [0.6002912500000004, 0.6170961631909572, 0.03095742520933848]
SVM_Model = [1.0629888299326313, 1.108937997325214, 0.054795037325405915]
MLP_Model = [0.9649075888395305, 1.077064989149656, 0.04990548687806204]
CNN_Model = [4.509283710479734, 4.5117083260225606, 0.23290656976043722]
LSTM_Model = [4.709705494801201, 4.7121318470347235, 0.2432610001943479]
GRU_Model = [4.647322945753731, 4.649675580133427, 0.24003811817786005]

N = 6
x = np.arange(N)
c = ['red', 'blue', 'green']
width = 0.3

# Set position of bar on X axis
r1 = np.arange(0, len(RF_Model) * 3, 3)
r2 = [x + width for x in r1]
r3 = [x + width for x in r2]
r4 = [x + width for x in r3]
r5 = [x + width for x in r4]
r6 = [x + width for x in r5]

plt.figure(figsize=(15, 8))
plt.ylabel("Error", weight='bold').set_fontsize('18')
plt.bar(r1, RF_Model, width, edgecolor='white', label='RF_Model')
plt.bar(r2, SVM_Model, width, edgecolor='white', label='SVM_Model')
plt.bar(r3, MLP_Model, width, edgecolor='white', label='MLP_Model')
plt.bar(r4, CNN_Model, width, edgecolor='white', label='CNN_Model')
plt.bar(r5, LSTM_Model, width, edgecolor='white', label='LSTM_Model')
plt.bar(r6, GRU_Model, width, edgecolor='white', label='GRU_Model')
plt.xlabel('METRICS', weight='bold').set_fontsize('18')
plt.xticks([r + width for r in range(0, len(RF_Model) * 3, 3)], ['MAE', 'RMSE', 'MAPE'], rotation=45, size = 12, fontweight='bold')
plt.title('Performance Comparison between All ML and DL Models in terms of all Metrics Before Augmentation', size = 18, fontweight='bold')
plt.legend(loc = 'best', bbox_to_anchor = (1.0, 1.0), ncol = 1, frameon=True, fontsize = '12')
plt.savefig('Performance Comparison between All ML and DL Models in terms of all Metrics.png')

"""Preliminary results obtained with just a few training data points (3200 training
data points) suggest that the RF and the SVM ML models performed better than
the DL models. This is expected because the DL architectures are designed to
be more efficient in handling larger datasets. It is also the reason why the
shallow MLP models performed better than the very deep DL models such as
the CNN, LSTM, and GRU models.

To this effect, we will now perform data augmentation to diversify and increase
the training data points and see how it affects the prediction accuracies of the
models.

**Data Augmentation for Sequence Data**

We will go ahead and add some diversity to the sample data. To achieve this, we can use "Data Augmentation" methods. We will use the simplest one in practice: adding some noise into real samples. The noise needs to be calibrated in order to keep the data structure, i.e it has to be small compared with the real standard deviation.

**Some Augmentation Methods**

All of the augmentation methods expect a numpy array x of size (batch, time_steps, channel) where batch is the size of the dataset or batch, time_steps is the number of time steps, and channel is the number of dimensions. Even if 1D time series are used, channel should still be 1.

1. Adding jittering, or noise, to the time series.
aug.jitter(x, sigma=0.03)

2. Scaling each time series by a constant amount.
aug.scaling(x, sigma=0.1)

3. Flipping/Rotation
aug.rotation(x)

4. Random permutation of segments. A random number of segments is used, up to max_segments.
aug.permutation(x, max_segments=5, seg_mode="equal")

5. Magnitude Warping
The magnitude of each time series is multiplied by a curve created by cubicspline with a set number of knots at random magnitudes.
aug.magnitude_warp(x, sigma=0.2, knot=4)

6. Time Warping
Random smooth time warping.
aug.time_warp(x, sigma=0.2, knot=4)

7. Window Slicing
Cropping the time series by the reduce_ratio
aug.window_slice(x, reduce_ratio=0.9)

8. Window Warping
Randomly warps a window by scales
aug.window_warp(x, window_ratio=0.1, scales=[0.5, 2.])

9. SuboPtimAl Warped time-series geNEratoR (SPAWNER)
aug.spawner(x, labels, sigma=0.05, verbose=0)

10.

**Obtain the Original Data**
"""

# Training Set - Optical Network from Sheffield to London and Ffom Sheffield to Endingurgh
df_train = pd.read_csv('/content/gdrive/MyDrive/Sheffield_London__Sheffield_Endinburgh_35_TRAIN.csv')

# Testing Set - Optical Network from Belfast to Glasgow
df_test = pd.read_csv('/content/gdrive/MyDrive/Belfast_Glasgow_35_TEST.csv')

"""In this study, we will use the tsaug module: a Python package for time series augmentation. It offers a set of augmentation methods for time series, as well as a simple API to connect multiple augmenters into a pipeline"""

df_train

"""**Augmenting Channel frequency (THz) data**

**Add Noise to the Channel frequency (THz) data**

tsaug.AddNoise Add random noise to time series.

The noise added to every time point of a time series is independent and identically distributed
"""

x_aug1 = df_train['Channel frequency (THz)'].values
plot(x_aug1, x_aug1)

import tsaug
X_aug_cf1, Y_aug_cf1 = tsaug.AddNoise(scale=0.01).augment(x_aug1, x_aug1)

plot(X_aug_cf1, Y_aug_cf1);

"""**tsaug.Convolve**
Convolve time series with a kernel window.
"""

x_aug1 = df_train['Channel frequency (THz)'].values
plot(x_aug1, x_aug1)

X_aug_cf2, Y_aug_cf2 = tsaug.Convolve(window="flattop", size=11).augment(x_aug1, x_aug1)

plot(X_aug_cf2, Y_aug_cf2);

"""**tsaug.Crop**
Crop random sub-sequences from time series.

To guarantee all output series have the same length, if the crop size is not deterministic, all crops must be resize to a fixed length.
"""

x_aug1 = df_train['Channel frequency (THz)'].values
plot(x_aug1, x_aug1)

X_aug_cf3, Y_aug_cf3 = tsaug.Crop(size=3200).augment(x_aug1, x_aug1)

plot(X_aug_cf3, Y_aug_cf3);

"""**tsaug.Drift**
Drift the value of time series.

The augmenter drifts the value of time series from its original values randomly and smoothly. The extent of drifting is controlled by the maximal drift and the number of drift points.
"""

x_aug1 = df_train['Channel frequency (THz)'].values
plot(x_aug1, x_aug1)

X_aug_cf4, Y_aug_cf4 = tsaug.Drift(max_drift=0.7, n_drift_points=5).augment(x_aug1, x_aug1)

plot(X_aug_cf4, Y_aug_cf4);

"""**tsaug.Dropout**

Dropout values of some random time points in time series.

Single time points or sub-sequences could be dropped out.
"""

x_aug1 = df_train['Channel frequency (THz)'].values
plot(x_aug1, x_aug1)

X_aug_cf5, Y_aug_cf5 = tsaug.Dropout(p=0.1, size=(1,5), fill=float("nan"), per_channel=True).augment(x_aug1, x_aug1)

plot(X_aug_cf5, Y_aug_cf5);

"""**tsaug.Pool**
Reduce the temporal resolution without changing the length.
"""

x_aug1 = df_train['Channel frequency (THz)'].values
plot(x_aug1, x_aug1)

X_aug_cf6, Y_aug_cf6 = tsaug.Pool(size=2).augment(x_aug1, x_aug1)

plot(X_aug_cf6, Y_aug_cf6);

"""**tsaug.Quantize**
Quantize time series to a level set.

Values in a time series are rounded to the nearest level in the level set.
"""

x_aug1 = df_train['Channel frequency (THz)'].values
plot(x_aug1, x_aug1)

X_aug_cf7, Y_aug_cf7 = tsaug.Quantize(n_levels=20).augment(x_aug1, x_aug1)

plot(X_aug_cf7, Y_aug_cf7);

"""**tsaug.Resize**
Change the temporal resolution of time series.

The resized time series is obtained by linear interpolation of the original time series.
"""

x_aug1 = df_train['Channel frequency (THz)'].values
plot(x_aug1, x_aug1)

X_aug_cf8, Y_aug_cf8 = tsaug.Resize(size=3200).augment(x_aug1, x_aug1)

plot(X_aug_cf8, Y_aug_cf8);

"""**tsaug.Reverse**
Reverse the time line of series.
"""

x_aug1 = df_train['Channel frequency (THz)'].values
plot(x_aug1, x_aug1)

X_aug_cf9, Y_aug_cf9 = tsaug.Reverse().augment(x_aug1, x_aug1)

plot(X_aug_cf9, Y_aug_cf9);

"""**tsaug.TimeWarp**
Random time warping.

The augmenter random changed the speed of timeline. The time warping is controlled by the number of speed changes and the maximal ratio of max/min speed.
"""

x_aug1 = df_train['Channel frequency (THz)'].values
plot(x_aug1, x_aug1)

X_aug_cf10, Y_aug_cf10 = tsaug.TimeWarp(n_speed_change=5, max_speed_ratio=3).augment(x_aug1, x_aug1)

plot(X_aug_cf10, Y_aug_cf10);

"""**Add all Channel frequency data together**"""

Channel_frequency = np.concatenate((x_aug1, X_aug_cf1, X_aug_cf2, X_aug_cf3, X_aug_cf4, X_aug_cf5, X_aug_cf6, X_aug_cf7, X_aug_cf8, X_aug_cf9, X_aug_cf10), axis=0)
Channel_frequency.shape

"""**Augmenting Channel power (dBm) data**

**Add Noise to the Channel power (dBm) data**

tsaug.AddNoise Add random noise to time series.

The noise added to every time point of a time series is independent and identically distributed
"""

x_aug1 = df_train['Channel power (dBm)'].values
plot(x_aug1, x_aug1)

import tsaug
X_aug_cf1, Y_aug_cf1 = tsaug.AddNoise(scale=0.01).augment(x_aug1, x_aug1)

plot(X_aug_cf1, Y_aug_cf1);

"""**tsaug.Convolve**
Convolve time series with a kernel window.
"""

x_aug1 = df_train['Channel power (dBm)'].values
plot(x_aug1, x_aug1)

X_aug_cf2, Y_aug_cf2 = tsaug.Convolve(window="flattop", size=11).augment(x_aug1, x_aug1)

plot(X_aug_cf2, Y_aug_cf2);

"""**tsaug.Crop**
Crop random sub-sequences from time series.

To guarantee all output series have the same length, if the crop size is not deterministic, all crops must be resize to a fixed length.
"""

x_aug1 = df_train['Channel power (dBm)'].values
plot(x_aug1, x_aug1)

X_aug_cf3, Y_aug_cf3 = tsaug.Crop(size=3200).augment(x_aug1, x_aug1)

plot(X_aug_cf3, Y_aug_cf3);

"""**tsaug.Drift**
Drift the value of time series.

The augmenter drifts the value of time series from its original values randomly and smoothly. The extent of drifting is controlled by the maximal drift and the number of drift points.
"""

x_aug1 = df_train['Channel power (dBm)'].values
plot(x_aug1, x_aug1)

X_aug_cf4, Y_aug_cf4 = tsaug.Drift(max_drift=0.7, n_drift_points=5).augment(x_aug1, x_aug1)

plot(X_aug_cf4, Y_aug_cf4);

"""**tsaug.Dropout**

Dropout values of some random time points in time series.

Single time points or sub-sequences could be dropped out.
"""

x_aug1 = df_train['Channel power (dBm)'].values
plot(x_aug1, x_aug1)

X_aug_cf5, Y_aug_cf5 = tsaug.Dropout(p=0.1, size=(1,5), fill=float("nan"), per_channel=True).augment(x_aug1, x_aug1)

plot(X_aug_cf5, Y_aug_cf5);

"""**tsaug.Pool**
Reduce the temporal resolution without changing the length.
"""

x_aug1 = df_train['Channel power (dBm)'].values
plot(x_aug1, x_aug1)

X_aug_cf6, Y_aug_cf6 = tsaug.Pool(size=2).augment(x_aug1, x_aug1)

plot(X_aug_cf6, Y_aug_cf6);

"""**tsaug.Quantize**
Quantize time series to a level set.

Values in a time series are rounded to the nearest level in the level set.
"""

x_aug1 = df_train['Channel power (dBm)'].values
plot(x_aug1, x_aug1)

X_aug_cf7, Y_aug_cf7 = tsaug.Quantize(n_levels=20).augment(x_aug1, x_aug1)

plot(X_aug_cf7, Y_aug_cf7);

"""**tsaug.Resize**
Change the temporal resolution of time series.

The resized time series is obtained by linear interpolation of the original time series.
"""

x_aug1 = df_train['Channel power (dBm)'].values
plot(x_aug1, x_aug1)

X_aug_cf8, Y_aug_cf8 = tsaug.Resize(size=3200).augment(x_aug1, x_aug1)

plot(X_aug_cf8, Y_aug_cf8);

"""**tsaug.Reverse**
Reverse the time line of series.
"""

x_aug1 = df_train['Channel power (dBm)'].values
plot(x_aug1, x_aug1)

X_aug_cf9, Y_aug_cf9 = tsaug.Reverse().augment(x_aug1, x_aug1)

plot(X_aug_cf9, Y_aug_cf9);

"""**tsaug.TimeWarp**
Random time warping.

The augmenter random changed the speed of timeline. The time warping is controlled by the number of speed changes and the maximal ratio of max/min speed.
"""

x_aug1 = df_train['Channel power (dBm)'].values
plot(x_aug1, x_aug1)

X_aug_cf10, Y_aug_cf10 = tsaug.TimeWarp(n_speed_change=5, max_speed_ratio=3).augment(x_aug1, x_aug1)

plot(X_aug_cf10, Y_aug_cf10);

"""**Add all Channel power data together**"""

Channel_power = np.concatenate((x_aug1, X_aug_cf1, X_aug_cf2, X_aug_cf3, X_aug_cf4, X_aug_cf5, X_aug_cf6, X_aug_cf7, X_aug_cf8, X_aug_cf9, X_aug_cf10), axis=0)
Channel_power.shape

"""**Augmenting OSNR ASE (signal bw, dB) data**

**Add Noise to the OSNR ASE data**

tsaug.AddNoise Add random noise to time series.

The noise added to every time point of a time series is independent and identically distributed
"""

x_aug1 = df_train['OSNR ASE (signal bw, dB)'].values
plot(x_aug1, x_aug1)

import tsaug
X_aug_cf1, Y_aug_cf1 = tsaug.AddNoise(scale=0.01).augment(x_aug1, x_aug1)

plot(X_aug_cf1, Y_aug_cf1);

"""**tsaug.Convolve**
Convolve time series with a kernel window.
"""

x_aug1 = df_train['OSNR ASE (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf2, Y_aug_cf2 = tsaug.Convolve(window="flattop", size=11).augment(x_aug1, x_aug1)

plot(X_aug_cf2, Y_aug_cf2);

"""**tsaug.Crop**
Crop random sub-sequences from time series.

To guarantee all output series have the same length, if the crop size is not deterministic, all crops must be resize to a fixed length.
"""

x_aug1 = df_train['OSNR ASE (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf3, Y_aug_cf3 = tsaug.Crop(size=3200).augment(x_aug1, x_aug1)

plot(X_aug_cf3, Y_aug_cf3);

"""**tsaug.Drift**
Drift the value of time series.

The augmenter drifts the value of time series from its original values randomly and smoothly. The extent of drifting is controlled by the maximal drift and the number of drift points.
"""

x_aug1 = df_train['OSNR ASE (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf4, Y_aug_cf4 = tsaug.Drift(max_drift=0.7, n_drift_points=5).augment(x_aug1, x_aug1)

plot(X_aug_cf4, Y_aug_cf4);

"""**tsaug.Dropout**

Dropout values of some random time points in time series.

Single time points or sub-sequences could be dropped out.
"""

x_aug1 = df_train['OSNR ASE (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf5, Y_aug_cf5 = tsaug.Dropout(p=0.1, size=(1,5), fill=float("nan"), per_channel=True).augment(x_aug1, x_aug1)

plot(X_aug_cf5, Y_aug_cf5);

"""**tsaug.Pool**
Reduce the temporal resolution without changing the length.
"""

x_aug1 = df_train['OSNR ASE (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf6, Y_aug_cf6 = tsaug.Pool(size=2).augment(x_aug1, x_aug1)

plot(X_aug_cf6, Y_aug_cf6);

"""**tsaug.Quantize**
Quantize time series to a level set.

Values in a time series are rounded to the nearest level in the level set.
"""

x_aug1 = df_train['OSNR ASE (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf7, Y_aug_cf7 = tsaug.Quantize(n_levels=20).augment(x_aug1, x_aug1)

plot(X_aug_cf7, Y_aug_cf7);

"""**tsaug.Resize**
Change the temporal resolution of time series.

The resized time series is obtained by linear interpolation of the original time series.
"""

x_aug1 = df_train['OSNR ASE (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf8, Y_aug_cf8 = tsaug.Resize(size=3200).augment(x_aug1, x_aug1)

plot(X_aug_cf8, Y_aug_cf8);

"""**tsaug.Reverse**
Reverse the time line of series.
"""

x_aug1 = df_train['OSNR ASE (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf9, Y_aug_cf9 = tsaug.Reverse().augment(x_aug1, x_aug1)

plot(X_aug_cf9, Y_aug_cf9);

"""**tsaug.TimeWarp**
Random time warping.

The augmenter random changed the speed of timeline. The time warping is controlled by the number of speed changes and the maximal ratio of max/min speed.
"""

x_aug1 = df_train['OSNR ASE (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf10, Y_aug_cf10 = tsaug.TimeWarp(n_speed_change=5, max_speed_ratio=3).augment(x_aug1, x_aug1)

plot(X_aug_cf10, Y_aug_cf10);

"""**Add all Channel frequency data together**"""

OSNR_ASE = np.concatenate((x_aug1, X_aug_cf1, X_aug_cf2, X_aug_cf3, X_aug_cf4, X_aug_cf5, X_aug_cf6, X_aug_cf7, X_aug_cf8, X_aug_cf9, X_aug_cf10), axis=0)
OSNR_ASE.shape

"""**Augmenting SNR NLI (signal bw, dB) data**

**Add Noise to the SNR NLI (signal bw, dB) data**

tsaug.AddNoise Add random noise to time series.

The noise added to every time point of a time series is independent and identically distributed
"""

x_aug1 = df_train['SNR NLI (signal bw, dB)'].values
plot(x_aug1, x_aug1)

import tsaug
X_aug_cf1, Y_aug_cf1 = tsaug.AddNoise(scale=0.01).augment(x_aug1, x_aug1)

plot(X_aug_cf1, Y_aug_cf1);

"""**tsaug.Convolve**
Convolve time series with a kernel window.
"""

x_aug1 = df_train['SNR NLI (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf2, Y_aug_cf2 = tsaug.Convolve(window="flattop", size=11).augment(x_aug1, x_aug1)

plot(X_aug_cf2, Y_aug_cf2);

"""**tsaug.Crop**
Crop random sub-sequences from time series.

To guarantee all output series have the same length, if the crop size is not deterministic, all crops must be resize to a fixed length.
"""

x_aug1 = df_train['SNR NLI (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf3, Y_aug_cf3 = tsaug.Crop(size=3200).augment(x_aug1, x_aug1)

plot(X_aug_cf3, Y_aug_cf3);

"""**tsaug.Drift**
Drift the value of time series.

The augmenter drifts the value of time series from its original values randomly and smoothly. The extent of drifting is controlled by the maximal drift and the number of drift points.
"""

x_aug1 = df_train['SNR NLI (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf4, Y_aug_cf4 = tsaug.Drift(max_drift=0.7, n_drift_points=5).augment(x_aug1, x_aug1)

plot(X_aug_cf4, Y_aug_cf4);

"""**tsaug.Dropout**

Dropout values of some random time points in time series.

Single time points or sub-sequences could be dropped out.
"""

x_aug1 = df_train['SNR NLI (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf5, Y_aug_cf5 = tsaug.Dropout(p=0.1, size=(1,5), fill=float("nan"), per_channel=True).augment(x_aug1, x_aug1)

plot(X_aug_cf5, Y_aug_cf5);

"""**tsaug.Pool**
Reduce the temporal resolution without changing the length.
"""

x_aug1 = df_train['SNR NLI (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf6, Y_aug_cf6 = tsaug.Pool(size=2).augment(x_aug1, x_aug1)

plot(X_aug_cf6, Y_aug_cf6);

"""**tsaug.Quantize**
Quantize time series to a level set.

Values in a time series are rounded to the nearest level in the level set.
"""

x_aug1 = df_train['SNR NLI (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf7, Y_aug_cf7 = tsaug.Quantize(n_levels=20).augment(x_aug1, x_aug1)

plot(X_aug_cf7, Y_aug_cf7);

"""**tsaug.Resize**
Change the temporal resolution of time series.

The resized time series is obtained by linear interpolation of the original time series.
"""

x_aug1 = df_train['SNR NLI (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf8, Y_aug_cf8 = tsaug.Resize(size=3200).augment(x_aug1, x_aug1)

plot(X_aug_cf8, Y_aug_cf8);

"""**tsaug.Reverse**
Reverse the time line of series.
"""

x_aug1 = df_train['SNR NLI (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf9, Y_aug_cf9 = tsaug.Reverse().augment(x_aug1, x_aug1)

plot(X_aug_cf9, Y_aug_cf9);

"""**tsaug.TimeWarp**
Random time warping.

The augmenter random changed the speed of timeline. The time warping is controlled by the number of speed changes and the maximal ratio of max/min speed.
"""

x_aug1 = df_train['SNR NLI (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf10, Y_aug_cf10 = tsaug.TimeWarp(n_speed_change=5, max_speed_ratio=3).augment(x_aug1, x_aug1)

plot(X_aug_cf10, Y_aug_cf10);

"""**Add all Channel frequency data together**"""

SNR_NLI = np.concatenate((x_aug1, X_aug_cf1, X_aug_cf2, X_aug_cf3, X_aug_cf4, X_aug_cf5, X_aug_cf6, X_aug_cf7, X_aug_cf8, X_aug_cf9, X_aug_cf10), axis=0)
SNR_NLI.shape

"""**Augmenting Span data**

**Add Noise to the Span data**

tsaug.AddNoise Add random noise to time series.

The noise added to every time point of a time series is independent and identically distributed
"""

x_aug1 = df_train['Span'].values
plot(x_aug1, x_aug1)

import tsaug
X_aug_cf1, Y_aug_cf1 = tsaug.AddNoise(scale=0.01).augment(x_aug1, x_aug1)

plot(X_aug_cf1, Y_aug_cf1);

"""**tsaug.Convolve**
Convolve time series with a kernel window.
"""

x_aug1 = df_train['Span'].values
plot(x_aug1, x_aug1)

X_aug_cf2, Y_aug_cf2 = tsaug.Convolve(window="flattop", size=11).augment(x_aug1, x_aug1)

plot(X_aug_cf2, Y_aug_cf2);

"""**tsaug.Crop**
Crop random sub-sequences from time series.

To guarantee all output series have the same length, if the crop size is not deterministic, all crops must be resize to a fixed length.
"""

x_aug1 = df_train['Span'].values
plot(x_aug1, x_aug1)

X_aug_cf3, Y_aug_cf3 = tsaug.Crop(size=3200).augment(x_aug1, x_aug1)

plot(X_aug_cf3, Y_aug_cf3);

"""**tsaug.Drift**
Drift the value of time series.

The augmenter drifts the value of time series from its original values randomly and smoothly. The extent of drifting is controlled by the maximal drift and the number of drift points.
"""

x_aug1 = df_train['Span'].values
plot(x_aug1, x_aug1)

X_aug_cf4, Y_aug_cf4 = tsaug.Drift(max_drift=0.7, n_drift_points=5).augment(x_aug1, x_aug1)

plot(X_aug_cf4, Y_aug_cf4);

"""**tsaug.Dropout**

Dropout values of some random time points in time series.

Single time points or sub-sequences could be dropped out.
"""

x_aug1 = df_train['Span'].values
plot(x_aug1, x_aug1)

X_aug_cf5, Y_aug_cf5 = tsaug.Dropout(p=0.1, size=(1,5), per_channel=True).augment(x_aug1, x_aug1)

plot(X_aug_cf5, Y_aug_cf5);

"""**tsaug.Pool**
Reduce the temporal resolution without changing the length.
"""

x_aug1 = df_train['Span'].values
plot(x_aug1, x_aug1)

X_aug_cf6, Y_aug_cf6 = tsaug.Pool(size=2).augment(x_aug1, x_aug1)

plot(X_aug_cf6, Y_aug_cf6);

"""**tsaug.Quantize**
Quantize time series to a level set.

Values in a time series are rounded to the nearest level in the level set.
"""

x_aug1 = df_train['Span'].values
plot(x_aug1, x_aug1)

X_aug_cf7, Y_aug_cf7 = tsaug.Quantize(n_levels=20).augment(x_aug1, x_aug1)

plot(X_aug_cf7, Y_aug_cf7);

"""**tsaug.Resize**
Change the temporal resolution of time series.

The resized time series is obtained by linear interpolation of the original time series.
"""

x_aug1 = df_train['Span'].values
plot(x_aug1, x_aug1)

X_aug_cf8, Y_aug_cf8 = tsaug.Resize(size=3200).augment(x_aug1, x_aug1)

plot(X_aug_cf8, Y_aug_cf8);

"""**tsaug.Reverse**
Reverse the time line of series.
"""

x_aug1 = df_train['Span'].values
plot(x_aug1, x_aug1)

X_aug_cf9, Y_aug_cf9 = tsaug.Reverse().augment(x_aug1, x_aug1)

plot(X_aug_cf9, Y_aug_cf9);

"""**tsaug.TimeWarp**
Random time warping.

The augmenter random changed the speed of timeline. The time warping is controlled by the number of speed changes and the maximal ratio of max/min speed.
"""

x_aug1 = df_train['Span'].values
plot(x_aug1, x_aug1)

X_aug_cf10, Y_aug_cf10 = tsaug.TimeWarp(n_speed_change=5, max_speed_ratio=3).augment(x_aug1, x_aug1)

plot(X_aug_cf10, Y_aug_cf10);

"""**Add all Channel frequency data together**"""

Span = np.concatenate((x_aug1, X_aug_cf1, X_aug_cf2, X_aug_cf3, X_aug_cf4, X_aug_cf5, X_aug_cf6, X_aug_cf7, X_aug_cf8, X_aug_cf9, X_aug_cf10), axis=0)
Span.shape

"""**Augmenting Distance (km) data**

**Add Noise to the Distance (km) data**

tsaug.AddNoise Add random noise to time series.

The noise added to every time point of a time series is independent and identically distributed
"""

x_aug1 = df_train['Distance (km)'].values
plot(x_aug1, x_aug1)

import tsaug
X_aug_cf1, Y_aug_cf1 = tsaug.AddNoise(scale=0.01).augment(x_aug1, x_aug1)

plot(X_aug_cf1, Y_aug_cf1);

"""**tsaug.Convolve**
Convolve time series with a kernel window.
"""

x_aug1 = df_train['Distance (km)'].values
plot(x_aug1, x_aug1)

X_aug_cf2, Y_aug_cf2 = tsaug.Convolve(window="flattop", size=11).augment(x_aug1, x_aug1)

plot(X_aug_cf2, Y_aug_cf2);

"""**tsaug.Crop**
Crop random sub-sequences from time series.

To guarantee all output series have the same length, if the crop size is not deterministic, all crops must be resize to a fixed length.
"""

x_aug1 = df_train['Distance (km)'].values
plot(x_aug1, x_aug1)

X_aug_cf3, Y_aug_cf3 = tsaug.Crop(size=3200).augment(x_aug1, x_aug1)

plot(X_aug_cf3, Y_aug_cf3);

"""**tsaug.Drift**
Drift the value of time series.

The augmenter drifts the value of time series from its original values randomly and smoothly. The extent of drifting is controlled by the maximal drift and the number of drift points.
"""

x_aug1 = df_train['Distance (km)'].values
plot(x_aug1, x_aug1)

X_aug_cf4, Y_aug_cf4 = tsaug.Drift(max_drift=0.7, n_drift_points=5).augment(x_aug1, x_aug1)

plot(X_aug_cf4, Y_aug_cf4);

"""**tsaug.Dropout**

Dropout values of some random time points in time series.

Single time points or sub-sequences could be dropped out.
"""

x_aug1 = df_train['Distance (km)'].values
plot(x_aug1, x_aug1)

X_aug_cf5, Y_aug_cf5 = tsaug.Dropout(p=0.1, size=(1,5), per_channel=True).augment(x_aug1, x_aug1)

plot(X_aug_cf5, Y_aug_cf5);

"""**tsaug.Pool**
Reduce the temporal resolution without changing the length.
"""

x_aug1 = df_train['Distance (km)'].values
plot(x_aug1, x_aug1)

X_aug_cf6, Y_aug_cf6 = tsaug.Pool(size=2).augment(x_aug1, x_aug1)

plot(X_aug_cf6, Y_aug_cf6);

"""**tsaug.Quantize**
Quantize time series to a level set.

Values in a time series are rounded to the nearest level in the level set.
"""

x_aug1 = df_train['Distance (km)'].values
plot(x_aug1, x_aug1)

X_aug_cf7, Y_aug_cf7 = tsaug.Quantize(n_levels=20).augment(x_aug1, x_aug1)

plot(X_aug_cf7, Y_aug_cf7);

"""**tsaug.Resize**
Change the temporal resolution of time series.

The resized time series is obtained by linear interpolation of the original time series.
"""

x_aug1 = df_train['Distance (km)'].values
plot(x_aug1, x_aug1)

X_aug_cf8, Y_aug_cf8 = tsaug.Resize(size=3200).augment(x_aug1, x_aug1)

plot(X_aug_cf8, Y_aug_cf8);

"""**tsaug.Reverse**
Reverse the time line of series.
"""

x_aug1 = df_train['Distance (km)'].values
plot(x_aug1, x_aug1)

X_aug_cf9, Y_aug_cf9 = tsaug.Reverse().augment(x_aug1, x_aug1)

plot(X_aug_cf9, Y_aug_cf9);

"""**tsaug.TimeWarp**
Random time warping.

The augmenter random changed the speed of timeline. The time warping is controlled by the number of speed changes and the maximal ratio of max/min speed.
"""

x_aug1 = df_train['Distance (km)'].values
plot(x_aug1, x_aug1)

X_aug_cf10, Y_aug_cf10 = tsaug.TimeWarp(n_speed_change=5, max_speed_ratio=3).augment(x_aug1, x_aug1)

plot(X_aug_cf10, Y_aug_cf10);

"""**Add all Channel frequency data together**"""

Distance = np.concatenate((x_aug1, X_aug_cf1, X_aug_cf2, X_aug_cf3, X_aug_cf4, X_aug_cf5, X_aug_cf6, X_aug_cf7, X_aug_cf8, X_aug_cf9, X_aug_cf10), axis=0)
Distance.shape

"""**Augmenting SNR total (signal bw, dB) data**

**Add Noise to the SNR total (signal bw, dB) data**

tsaug.AddNoise Add random noise to time series.

The noise added to every time point of a time series is independent and identically distributed
"""

x_aug1 = df_train['SNR total (signal bw, dB)'].values
plot(x_aug1, x_aug1)

import tsaug
X_aug_cf1, Y_aug_cf1 = tsaug.AddNoise(scale=0.01).augment(x_aug1, x_aug1)

plot(X_aug_cf1, Y_aug_cf1);

"""**tsaug.Convolve**
Convolve time series with a kernel window.
"""

x_aug1 = df_train['SNR total (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf2, Y_aug_cf2 = tsaug.Convolve(window="flattop", size=11).augment(x_aug1, x_aug1)

plot(X_aug_cf2, Y_aug_cf2);

"""**tsaug.Crop**
Crop random sub-sequences from time series.

To guarantee all output series have the same length, if the crop size is not deterministic, all crops must be resize to a fixed length.
"""

x_aug1 = df_train['SNR total (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf3, Y_aug_cf3 = tsaug.Crop(size=3200).augment(x_aug1, x_aug1)

plot(X_aug_cf3, Y_aug_cf3);

"""**tsaug.Drift**
Drift the value of time series.

The augmenter drifts the value of time series from its original values randomly and smoothly. The extent of drifting is controlled by the maximal drift and the number of drift points.
"""

x_aug1 = df_train['SNR total (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf4, Y_aug_cf4 = tsaug.Drift(max_drift=0.7, n_drift_points=5).augment(x_aug1, x_aug1)

plot(X_aug_cf4, Y_aug_cf4);

"""**tsaug.Dropout**

Dropout values of some random time points in time series.

Single time points or sub-sequences could be dropped out.
"""

x_aug1 = df_train['SNR total (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf5, Y_aug_cf5 = tsaug.Dropout(p=0.1, size=(1,5), fill=float("nan"), per_channel=True).augment(x_aug1, x_aug1)

plot(X_aug_cf5, Y_aug_cf5);

"""**tsaug.Pool**
Reduce the temporal resolution without changing the length.
"""

x_aug1 = df_train['SNR total (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf6, Y_aug_cf6 = tsaug.Pool(size=2).augment(x_aug1, x_aug1)

plot(X_aug_cf6, Y_aug_cf6);

"""**tsaug.Quantize**
Quantize time series to a level set.

Values in a time series are rounded to the nearest level in the level set.
"""

x_aug1 = df_train['SNR total (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf7, Y_aug_cf7 = tsaug.Quantize(n_levels=20).augment(x_aug1, x_aug1)

plot(X_aug_cf7, Y_aug_cf7);

"""**tsaug.Resize**
Change the temporal resolution of time series.

The resized time series is obtained by linear interpolation of the original time series.
"""

x_aug1 = df_train['SNR total (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf8, Y_aug_cf8 = tsaug.Resize(size=3200).augment(x_aug1, x_aug1)

plot(X_aug_cf8, Y_aug_cf8);

"""**tsaug.Reverse**
Reverse the time line of series.
"""

x_aug1 = df_train['SNR total (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf9, Y_aug_cf9 = tsaug.Reverse().augment(x_aug1, x_aug1)

plot(X_aug_cf9, Y_aug_cf9);

"""**tsaug.TimeWarp**
Random time warping.

The augmenter random changed the speed of timeline. The time warping is controlled by the number of speed changes and the maximal ratio of max/min speed.
"""

x_aug1 = df_train['SNR total (signal bw, dB)'].values
plot(x_aug1, x_aug1)

X_aug_cf10, Y_aug_cf10 = tsaug.TimeWarp(n_speed_change=5, max_speed_ratio=3).augment(x_aug1, x_aug1)

plot(X_aug_cf10, Y_aug_cf10);

"""**Add all Channel frequency data together**"""

SNR_total = np.concatenate((x_aug1, X_aug_cf1, X_aug_cf2, X_aug_cf3, X_aug_cf4, X_aug_cf5, X_aug_cf6, X_aug_cf7, X_aug_cf8, X_aug_cf9, X_aug_cf10), axis=0)
SNR_total.shape

"""**Put all data together in a DataFrame**"""

df_train_aug = pd.DataFrame({'Channel_frequency' : Channel_frequency, 'Channel_power' : Channel_power,
                             'OSNR_ASE' : OSNR_ASE, 'SNR_NLI' : SNR_NLI, 'Span' : Span,
                             'Distance' : Distance, 'SNR_total' : SNR_total})

df_train_aug = df_train_aug.replace([np.inf, -np.inf], np.nan)
df_train_aug = df_train_aug.dropna()
df_train_aug

"""**Begin Modelling with the Augmented Data**"""

# For Training Set:
y_ = df_train_aug['SNR_total'].values
x_ = df_train_aug.iloc[:, :-1]

# For Testing Set:
y_test = df_test['SNR total (signal bw, dB)']
X_test = df_test.iloc[:, :-1]

"""
   ii. Data Splitting - 80% train set and 20% val set:
"""
X_train, X_val, y_train, y_val = train_test_split(x_, y_, test_size=0.20, random_state=42)

"""
    Normalize the data:
    It is important to scale features before training a neural network. Normalization is a
    common way of doing this scaling: subtract the mean and divide by the standard deviation
    of each feature.
"""

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_val)
X_test = scaler.transform(X_test)

"""**Define Random Seed**"""

keras.backend.clear_session()
np.random.seed(42)
tf.random.set_seed(42)

"""**Define the Evaluation Metrics**"""

def MAE(pred, true):
    return tf.reduce_mean(tf.abs(pred - true))


def MSE(pred, true):
    return tf.reduce_mean((pred - true) ** 2)


def RMSE(pred, true):
    return tf.sqrt(MSE(pred, true))


def MAPE(pred, true):
    return tf.reduce_mean(tf.abs((pred - true) / true)) * 100


def metric(pred, true):
    mae = MAE(pred, true)
    mse = MSE(pred, true)
    rmse = RMSE(pred, true)
    mape = MAPE(pred, true)

    return mae, mse, rmse, mape

"""**Print the shape of the dataset**"""

print(X_train.shape)
print(X_val.shape)
print(X_test.shape)
print(y_train.shape)
print(y_val.shape)
print(y_test.shape)

"""**Model 1 - Random Forest (RF) Regressor:**

Here, we use Random Forest Regressor to fit to our training dataset & predict results.
"""

# instantiate the Regressor and fit to training data
start = time.time()

rf = RandomForestRegressor()
rf.fit(X_train, y_train)

end = time.time()
print('Time Taken: %.3f seconds' % (end-start))

# viewing params of random forest
rf.get_params()

all_models = list()
performance_all = {}

# making predictions on test set
start = time.time()

y_pred_rf = rf.predict(X_test)

end = time.time()
print('Time Taken: %.3f seconds' % (end-start))

print('Mean Absolute Error:', MAE(y_pred_rf, y_test))
print('Root Mean Square Error:', RMSE(y_pred_rf, y_test))
print('Mean Absolute Percentage Error:', MAPE(y_pred_rf, y_test))

performance_all['RF_Model'] = MAE(y_pred_rf, y_test), RMSE(y_pred_rf, y_test), MAPE(y_pred_rf, y_test)

model1 = rf
all_models.append(model1)

"""**Data Pre-processing for Model 2**"""

# For Training Set:
y_ = df_train_aug['SNR_total'].values
x_ = df_train_aug.iloc[:, :-1]

# For Testing Set:
y_test = df_test['SNR total (signal bw, dB)']
X_test = df_test.iloc[:, :-1]

"""
   ii. Data Splitting - 80% train set and 20% val set:
"""
X_train, X_val, y_train, y_val = train_test_split(x_, y_, test_size=0.20, random_state=42)

"""
    Normalize the data:
    It is important to scale features before training a neural network. Normalization is a
    common way of doing this scaling: subtract the mean and divide by the standard deviation
    of each feature.
"""

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_val)
X_test = scaler.transform(X_test)

"""**Model 2 - Support Vector Machine (SVM):**

Similar to RF Model, we'll fit SVM on our training dataset and check its performance on test data.
"""

# instantiate and fit SVM to train data

svc = SVR(C=1.0, epsilon=0.2)
clf = svc
clf.fit(X_train, y_train)

# check parameters of SVM
clf.get_params()

# making predictions on test set
start = time.time()

y_pred_svc = clf.predict(X_test)

end = time.time()
print('Time Taken: %.3f seconds' % (end-start))

print('Mean Absolute Error:', MAE(y_pred_svc, y_test))
print('Root Mean Square Error:', RMSE(y_pred_svc, y_test))
print('Mean Absolute Percentage Error:', MAPE(y_pred_svc, y_test))

performance_all['SVC_Model'] = MAE(y_pred_svc, y_test), RMSE(y_pred_svc, y_test), MAPE(y_pred_svc, y_test)

model2 = clf
all_models.append(model2)

"""**Data Pre-processing for Model 3**"""

# For Training Set:
y_ = df_train_aug['SNR_total'].values
x_ = df_train_aug.iloc[:, :-1]

# For Testing Set:
y_test = df_test['SNR total (signal bw, dB)']
X_test = df_test.iloc[:, :-1]

"""
   ii. Data Splitting - 80% train set and 20% val set:
"""
X_train, X_val, y_train, y_val = train_test_split(x_, y_, test_size=0.20, random_state=42)

"""
    Normalize the data:
    It is important to scale features before training a neural network. Normalization is a
    common way of doing this scaling: subtract the mean and divide by the standard deviation
    of each feature.
"""

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_val)
X_test = scaler.transform(X_test)

"""**Model 3:**

Build a Simple Multi-Layer Perceptron (MLP) Regression Model Uisng Subclassing API And Optimize the Hyperparameters:
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard

def build_model(n_hidden=1, n_neurons=30, learning_rate=3e-3, input_shape=[6]):
    model = keras.models.Sequential()
    model.add(keras.layers.InputLayer(input_shape=input_shape))
    for layer in range(n_hidden):
        model.add(keras.layers.Dense(n_neurons, kernel_initializer="he_normal", activation="relu"))
        model.add(keras.layers.BatchNormalization())
        model.add(keras.layers.Activation("relu"))
    model.add(keras.layers.Dense(1))
    optimizer = keras.optimizers.SGD(learning_rate=learning_rate)
    model.compile(loss="mse", optimizer=optimizer, metrics=[MAE, RMSE, MAPE])
    return model

early_stopping_cb = keras.callbacks.EarlyStopping(patience=10)
model_checkpoint_cb = keras.callbacks.ModelCheckpoint("MLP.h5", save_best_only=True)
run_index = 1 # increment every time you train the model
run_logdir = os.path.join(os.curdir, "my_MLP_logs", "run_bn_{:03d}".format(run_index))
tensorboard_cb = keras.callbacks.TensorBoard(run_logdir)
callbacks = [early_stopping_cb, model_checkpoint_cb, tensorboard_cb]

"""
    Hyperparameters Optimization Using Randomized Search Algorithm
"""
keras_reg = keras.wrappers.scikit_learn.KerasRegressor(build_model)

param_distribs = {
    "n_hidden": [1, 2, 3],
    "n_neurons": np.arange(1, 100)               .tolist(),
    "learning_rate": reciprocal(3e-4, 3e-2)      .rvs(1000).tolist(),
}

rnd_search_cv = RandomizedSearchCV(keras_reg, param_distribs, n_iter=10, cv=3, verbose=2)
rnd_search_cv.fit(X_train, y_train, epochs=100,
                  validation_data=(X_val, y_val),
                  callbacks=callbacks)

"""**Obtain the best Parameters, Score, trained model, and use it for evaluation**"""

print(rnd_search_cv.best_params_)
print(rnd_search_cv.best_score_)
rnd_search_cv.score(X_test, y_test)

model = rnd_search_cv.best_estimator_.model
model.evaluate(X_test, y_test)

"""**Make Predictions with the best trained Model:**"""

y_pred_MLP = model.predict(X_test)
y_pred_MLP = y_pred_MLP[:, -1]
performance_all['MLP_Model'] = MAE(y_pred_MLP, y_test), RMSE(y_pred_MLP, y_test), MAPE(y_pred_MLP, y_test)

"""**View the Model's Structure**"""

model.summary()

"""**Data Pre-processing for Model 4**"""

# For Training Set:
y_ = df_train_aug['SNR_total'].values
x_ = df_train_aug.iloc[:, :-1]

# For Testing Set:
y_test = df_test['SNR total (signal bw, dB)']
X_test = df_test.iloc[:, :-1]

"""
   ii. Data Splitting - 80% train set and 20% val set:
"""
X_train, X_val, y_train, y_val = train_test_split(x_, y_, test_size=0.20, random_state=42)

"""
    Normalize the data:
    It is important to scale features before training a neural network. Normalization is a
    common way of doing this scaling: subtract the mean and divide by the standard deviation
    of each feature.
"""

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_val)
X_test = scaler.transform(X_test)

"""**Model 4 - Convolutional Neural Network (CNN)**

**Compile, Build, and Perform Hyperparameters Optimization in order to Build the Deep Learning CNN Model:**

We will apply the CNN algorithm to our data to generate prediction results. First, we need to reshape our data for CNN.

We will use 1-dimensional CNN for our model, reshaping our data as per the dimensions of our CNN

Note that the timeseries data used here are univariate, meaning we only have one channel per timeseries example.
We will therefore transform the timeseries into a multivariate one with one channel using a simple
reshaping via numpy. This will allow us to construct a model that is easily applicable to multivariate time series


"""

# Commented out IPython magic to ensure Python compatibility.
X_val = X_val.values
# Reshape the Data:
X_train = X_train.reshape(len(X_train), X_train.shape[1], 1)
X_val = X_val.reshape(len(X_val), X_val.shape[1], 1)
X_test = X_test.reshape(len(X_test), X_test.shape[1], 1)
print(X_train.shape, X_val, X_test.shape)

# %load_ext tensorboard

def build_model(n_hidden=1, n_neurons=30, learning_rate=3e-3, input_shape=(6, 1)):
    model = keras.models.Sequential()
    model.add(keras.layers.InputLayer(input_shape=input_shape))
    for layer in range(n_hidden):
        model.add(Conv1D(n_neurons, kernel_size=2, activation='relu',
                    padding='same', input_shape=(6, 1)))
        model.add(keras.layers.BatchNormalization())
        model.add(MaxPooling1D(pool_size=(3), strides=2, padding='same'))
        model.add(keras.layers.Activation("relu"))
        model.add(Dropout(0.2))
    model.add(keras.layers.Dense(1))
    optimizer = keras.optimizers.SGD(learning_rate=learning_rate)
    model.compile(loss="mse", optimizer=optimizer, metrics=[MAE, RMSE, MAPE])
    return model

early_stopping_cb = keras.callbacks.EarlyStopping(patience=10)
model_checkpoint_cb = keras.callbacks.ModelCheckpoint("CNN.h5", save_best_only=True)
run_index = 1 # increment every time you train the model
run_logdir = os.path.join(os.curdir, "my_CNN_logs", "run_bn_{:03d}".format(run_index))
tensorboard_cb = keras.callbacks.TensorBoard(run_logdir)
callbacks = [early_stopping_cb, model_checkpoint_cb, tensorboard_cb]

"""
    Hyperparameters Optimization Using Randomized Search Algorithm
"""
keras_reg = keras.wrappers.scikit_learn.KerasRegressor(build_model)

param_distribs = {
    "n_hidden": [1, 2, 3],
    "n_neurons": np.arange(1, 100)               .tolist(),
    "learning_rate": reciprocal(3e-4, 3e-2)      .rvs(1000).tolist(),
}

rnd_search_cv = RandomizedSearchCV(keras_reg, param_distribs, n_iter=10, cv=3, verbose=2)
rnd_search_cv.fit(X_train, y_train, epochs=100,
                  validation_data=(X_val, y_val),
                  callbacks=callbacks)

"""**Obtain the best Parameters, Score, Best Trained Model and Use it for Evaluation**"""

print(rnd_search_cv.best_params_)
print(rnd_search_cv.best_score_)
rnd_search_cv.score(X_test, y_test)

model = rnd_search_cv.best_estimator_.model
model.evaluate(X_test, y_test)

"""**Make Predictions with the trained Model**"""

y_pred_CNN = model.predict(X_test)
y_pred_CNN = y_pred_CNN[:, -1, -1]
performance_all['CNN_Model'] = MAE(y_pred_CNN, y_test), RMSE(y_pred_CNN, y_test), MAPE(y_pred_CNN, y_test)

"""**View the Model's Structure**"""

model.summary()

"""**Data Pre-processing for Model 5**"""

# For Training Set:
y_ = df_train_aug['SNR_total'].values
x_ = df_train_aug.iloc[:, :-1]

# For Testing Set:
y_test = df_test['SNR total (signal bw, dB)']
X_test = df_test.iloc[:, :-1]

"""
   ii. Data Splitting - 80% train set and 20% val set:
"""
X_train, X_val, y_train, y_val = train_test_split(x_, y_, test_size=0.20, random_state=42)

"""
    Normalize the data:
    It is important to scale features before training a neural network. Normalization is a
    common way of doing this scaling: subtract the mean and divide by the standard deviation
    of each feature.
"""

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_val)
X_test = scaler.transform(X_test)

"""**Model 5 - Build the Long Short Term Memory Neural Network (LSTM) and Perform Hyperparameters Optimization Using Randomized Search Algorithm**"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard

def build_model(n_hidden=1, n_neurons=30, learning_rate=3e-3, input_shape=(6, 1)):
    model = keras.models.Sequential()
    model.add(keras.layers.InputLayer(input_shape=input_shape))
    for layer in range(n_hidden):
        model.add(keras.layers.LSTM(n_neurons, return_sequences=True, activation="relu"))
        model.add(keras.layers.BatchNormalization())
        model.add(keras.layers.Activation("relu"))
        model.add(Dropout(0.2))
    model.add(keras.layers.Dense(1))
    optimizer = keras.optimizers.SGD(learning_rate=learning_rate)
    model.compile(loss="mse", optimizer=optimizer, metrics=[MAE, RMSE, MAPE])
    return model

early_stopping_cb = keras.callbacks.EarlyStopping(patience=10)
model_checkpoint_cb = keras.callbacks.ModelCheckpoint("LSTM.h5", save_best_only=True)
run_index = 1 # increment every time you train the model
run_logdir = os.path.join(os.curdir, "my_LSTM_logs", "run_bn_{:03d}".format(run_index))
tensorboard_cb = keras.callbacks.TensorBoard(run_logdir)
callbacks = [early_stopping_cb, model_checkpoint_cb, tensorboard_cb]

"""
    Hyperparameters Optimization Using Randomized Search Algorithm
"""
keras_reg = keras.wrappers.scikit_learn.KerasRegressor(build_model)

param_distribs = {
    "n_hidden": [1, 2, 3],
    "n_neurons": np.arange(1, 100)               .tolist(),
    "learning_rate": reciprocal(3e-4, 3e-2)      .rvs(1000).tolist(),
}

rnd_search_cv = RandomizedSearchCV(keras_reg, param_distribs, n_iter=10, cv=3, verbose=2)
rnd_search_cv.fit(X_train, y_train, epochs=100,
                  validation_data=(X_val, y_val),
                  callbacks=callbacks)

"""**Obtain the best Parameters, Score, and Best Trained Model and Use it for Evaluation**"""

print(rnd_search_cv.best_params_)
print(rnd_search_cv.best_score_)
rnd_search_cv.score(X_test, y_test)

model = rnd_search_cv.best_estimator_.model
model.evaluate(X_test, y_test)

"""**Make Predictions with the Best trained Model:**"""

y_pred_LSTM = model.predict(X_test)
y_pred_LSTM = y_pred_LSTM[:, -1, -1]
performance_all['LSTM_Model'] = MAE(y_pred_LSTM, y_test), RMSE(y_pred_LSTM, y_test), MAPE(y_pred_LSTM, y_test)

"""**View the Model's Structure**"""

model.summary()

"""**Data Pre-processing for Model 6**"""

# For Training Set:
y_ = df_train_aug['SNR_total'].values
x_ = df_train_aug.iloc[:, :-1]

# For Testing Set:
y_test = df_test['SNR total (signal bw, dB)']
X_test = df_test.iloc[:, :-1]

"""
   ii. Data Splitting - 80% train set and 20% val set:
"""
X_train, X_val, y_train, y_val = train_test_split(x_, y_, test_size=0.20, random_state=42)

"""
    Normalize the data:
    It is important to scale features before training a neural network. Normalization is a
    common way of doing this scaling: subtract the mean and divide by the standard deviation
    of each feature.
"""

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_val)
X_test = scaler.transform(X_test)

"""**Model 6 - Gated Recurrent Unit Neural Network (GRU) and Perform Hyperparameters Optimization Using Randomized Search Algorithm**"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard

def build_model(n_hidden=1, n_neurons=30, learning_rate=3e-3, input_shape=(6, 1)):
    model = keras.models.Sequential()
    model.add(keras.layers.InputLayer(input_shape=input_shape))
    for layer in range(n_hidden):
        model.add(keras.layers.GRU(n_neurons, return_sequences=True, activation="relu"))
        model.add(keras.layers.BatchNormalization())
        model.add(keras.layers.Activation("relu"))
        model.add(Dropout(0.2))
    model.add(keras.layers.Dense(1))
    optimizer = keras.optimizers.SGD(learning_rate=learning_rate)
    model.compile(loss="mse", optimizer=optimizer, metrics=[MAE, RMSE, MAPE])
    return model

early_stopping_cb = keras.callbacks.EarlyStopping(patience=10)
model_checkpoint_cb = keras.callbacks.ModelCheckpoint("GRU.h5", save_best_only=True)
run_index = 1 # increment every time you train the model
run_logdir = os.path.join(os.curdir, "my_GRU_logs", "run_bn_{:03d}".format(run_index))
tensorboard_cb = keras.callbacks.TensorBoard(run_logdir)
callbacks = [early_stopping_cb, model_checkpoint_cb, tensorboard_cb]

"""
    Hyperparameters Optimization Using Randomized Search Algorithm
"""
keras_reg = keras.wrappers.scikit_learn.KerasRegressor(build_model)

param_distribs = {
    "n_hidden": [1, 2, 3],
    "n_neurons": np.arange(1, 100)               .tolist(),
    "learning_rate": reciprocal(3e-4, 3e-2)      .rvs(1000).tolist(),
}

rnd_search_cv = RandomizedSearchCV(keras_reg, param_distribs, n_iter=10, cv=3, verbose=2)
rnd_search_cv.fit(X_train, y_train, epochs=100,
                  validation_data=(X_val, y_val),
                  callbacks=callbacks)

"""**Obtain the best Parameters, Score, Best Trained Model and Use it for Evaluation**"""

print(rnd_search_cv.best_params_)
print(rnd_search_cv.best_score_)
rnd_search_cv.score(X_test, y_test)

model = rnd_search_cv.best_estimator_.model
model.evaluate(X_test, y_test)

"""**Make Predictions with the Best trained Model**"""

y_pred_GRU = model.predict(X_test)
y_pred_GRU = y_pred_GRU[:, -1, -1]
performance_all['GRU_Model'] = MAE(y_pred_GRU, y_test), RMSE(y_pred_GRU, y_test), MAPE(y_pred_GRU, y_test)

"""**View the Model's Structure**"""

model.summary()

performance_all

"""**Performance Comparison between All ML and DL Models in terms of all Metrics After Augmentation**"""

RF_Model = [0.3700, 0.3987, 1.9062]
SVM_Model = [0.4770, 0.5332, 2.4551]
MLP_Model = [0.7544, 0.7612, 3.8939]
CNN_Model = [4.5121, 4.5145, 23.3054]
LSTM_Model = [4.5078, 4.5114, 23.28218]
GRU_Model = [4.5208, 4.5232, 23.3503]


N = 6
x = np.arange(N)
c = ['red', 'blue', 'green']
width = 0.3

# Set position of bar on X axis
r1 = np.arange(0, len(RF_Model) * 3, 3)
r2 = [x + width for x in r1]
r3 = [x + width for x in r2]
r4 = [x + width for x in r3]
r5 = [x + width for x in r4]
r6 = [x + width for x in r5]

plt.figure(figsize=(15, 8))
plt.ylabel("Error", weight='bold').set_fontsize('18')
plt.bar(r1, RF_Model, width, edgecolor='white', label='RF_Model')
plt.bar(r2, SVM_Model, width, edgecolor='white', label='SVM_Model')
plt.bar(r3, MLP_Model, width, edgecolor='white', label='MLP_Model')
plt.bar(r4, CNN_Model, width, edgecolor='white', label='CNN_Model')
plt.bar(r5, LSTM_Model, width, edgecolor='white', label='LSTM_Model')
plt.bar(r6, GRU_Model, width, edgecolor='white', label='GRU_Model')
plt.xlabel('METRICS', weight='bold').set_fontsize('18')
plt.xticks([r + width for r in range(0, len(RF_Model) * 3, 3)], ['MAE', 'RMSE', 'MAPE'], rotation=45, size = 12, fontweight='bold')
plt.title('Performance Comparison between All ML and DL Models in terms of all Metrics After Augmentation', size = 15, fontweight='bold')
plt.legend(loc = 'best', bbox_to_anchor = (1.0, 1.0), ncol = 1, frameon=True, fontsize = '12')
plt.savefig('Performance Comparison between All ML and DL Models in terms of all Metrics.png')

"""**Performance Comparison between All ML and DL Models in terms of all Metrics Before and After Augmentation**"""

RF_Model = [0.6002912500000004, 0.6170961631909572, 0.03095742520933848, 0.3700, 0.3987, 1.9062]
SVM_Model = [1.0629888299326313, 1.108937997325214, 0.054795037325405915, 0.4770, 0.5332, 2.4551]
MLP_Model = [0.9649075888395305, 1.077064989149656, 0.04990548687806204, 0.7544, 0.7612, 3.8939]
CNN_Model = [4.509283710479734, 4.5117083260225606, 0.23290656976043722, 4.5121, 4.5145, 23.3054]
LSTM_Model = [4.709705494801201, 4.7121318470347235, 0.2432610001943479, 4.5078, 4.5114, 23.28218]
GRU_Model = [4.647322945753731, 4.649675580133427, 0.24003811817786005, 4.5208, 4.5232, 23.3503]

N = 6
x = np.arange(N)
c = ['red', 'blue', 'green']
width = 0.3

# Set position of bar on X axis
r1 = np.arange(0, len(RF_Model) * 3, 3)
r2 = [x + width for x in r1]
r3 = [x + width for x in r2]
r4 = [x + width for x in r3]
r5 = [x + width for x in r4]
r6 = [x + width for x in r5]

plt.figure(figsize=(15, 8))
plt.ylabel("Error", weight='bold').set_fontsize('18')
plt.bar(r1, RF_Model, width, edgecolor='white', label='RF_Model')
plt.bar(r2, SVM_Model, width, edgecolor='white', label='SVM_Model')
plt.bar(r3, MLP_Model, width, edgecolor='white', label='MLP_Model')
plt.bar(r4, CNN_Model, width, edgecolor='white', label='CNN_Model')
plt.bar(r5, LSTM_Model, width, edgecolor='white', label='LSTM_Model')
plt.bar(r6, GRU_Model, width, edgecolor='white', label='GRU_Model')
plt.xlabel('METRICS', weight='bold').set_fontsize('18')
plt.xticks([r + width for r in range(0, len(RF_Model) * 3, 3)], ['MAE_B4AUG', 'RMSE_B4AUG', 'MAPE_B4AUG', 'MAE_AFTAUG', 'RMSE_AFTAUG', 'MAPE_AFTAUG'], rotation=45, size = 12, fontweight='bold')
plt.title('Performance Comparison between All ML and DL Models in terms of all Metrics After Augmentation', size = 15, fontweight='bold')
plt.legend(loc = 'best', bbox_to_anchor = (1.0, 1.0), ncol = 1, frameon=True, fontsize = '12')
plt.savefig('Performance Comparison between All ML and DL Models in terms of all Metrics.png')